### PR TITLE
DevKit updates for master branch

### PR DESCRIPTION
**Pull request by SonataCI**

### CODE REVIEW

**Comment by jordisala1991** [comment]
Also, @dbu can you check if we can remove a branch called `compatibility`?

**Comment by dbu** [comment]
@ElectricMaxxx created the commits in the `compatibility` branch. max, are those commits still relevant or can we remove the branch?

**Comment by dbu** [comment]
there is #509 that was merged, but there the compatibility branch is in @ElectricMaxxx fork of this repo... i guess we can delete the branch then, it probably got accidentally pushed to upstream?

**Comment by jordisala1991** [comment]
@dbu do you know why this happens? Can't we have an entity with `:void` as a return type on a method? I mean, I can force them all to return this so we don't get bother by this, but doesn't seem a solution to me.

https://travis-ci.org/sonata-project/SonataDoctrinePhpcrAdminBundle/jobs/326118558#L845

**Comment by dbu** [comment]
in OO, an extending class my only narrow the return type of a method to a subclass of what the parent declares. PHP does not implement that afaik. but afaik no language would allow to widen the type. the proxies use inheritance, hence they must also do the return types. as this only happens on the lowest build, it must be some dependency that is installed in a too old version - my guess would be the proxy generator.

**Comment by jordisala1991** [comment]
Proxy generator is a dependency directly declared here or it is from another bundle?
If it is on another bundle I would need to update that dependency and release that other bundle to make this work?

**Comment by dbu** [comment]
its no direct dependency. i tried finding what version is installed in a green vs the red build, but can't find that in the build log. i guess we should bump the dependency on phpcr-odm to 2.0

**Comment by jordisala1991** [comment]
I think the package that causes this issue is doctrine-common

**Comment by dbu** [comment]
> I think the package that causes this issue is doctrine-common

probably. can you find which version adds the return type declaration support and we add a conflict with versions lower than that?

**Comment by jordisala1991** [comment]
https://github.com/symfony-cmf/testing/pull/169

This one will fix this build

**Comment by jordisala1991** [comment]
Aaaand it seems to be working finally :)

**Comment by jordisala1991** [comment]
```
[PHPCR] Error when initializing dbal: 
In CheckExceptionOnInvalidReferenceBehaviorPass.php line 32:
                                                                               
  The service "jms_serializer.stopwatch_subscriber" has a dependency on a non  
  -existent service "debug.stopwatch".                                         
```

And now another error, this time is different, and it has no sense because all they builds passing but the admin 3.x is not

**Comment by dbu** [comment]
do we install a different version of jms serializer or (i guess) symfony/debug in the build that fails? or a different framework bundle? those would be the things that are involved with those services. or a different version of jackalope or doctrine dbal that does something different with the serializer?

**Comment by jordisala1991** [comment]
The only difference is that we use the 3.x branch instead of a tag, but that shouldnt change things... or atleast I dont remember any change affected by this...

**Comment by dbu** [comment]
do you manage to reproduce the problem locally? that might give some indication of what is happening...

**Comment by ElectricMaxxx** [comment]
@dbu is that question still relevant for me? I can not find any branch with that name atm?

**Comment by jordisala1991** [comment]
I removed it because of what dbu said

**Comment by dbu** [comment]
i merged 2.x to master and now rebased this branch on master. lets see!

**Comment by jordisala1991** [comment]
Done, thank you @dbu

**Pull request merged**
