### PR TITLE
add use statement for Options

### PR DESCRIPTION
**Pull request by ElectricMaxxx**
This PR will add the use statement for the Options Class ued in the `TreeBlockService`.

### CODE REVIEW

**Comment by OskarStark** [comment]
LGTM 👍

**Comment by OskarStark** [comment]
This should be submitted against '1.x'

**Comment by Soullivaneuh** [comment]
> This should be submitted against '1.x'

Does 1.x have the same issue?

**Comment by OskarStark** [comment]
> Does 1.x have the same issue?

Will check that

**Comment by OskarStark** [comment]
You are right @Soullivaneuh, everything is fine there!

Lets merge it please!

**Comment by Soullivaneuh** [comment]
Thank you @ElectricMaxxx

**Pull request merged**
