### PR TITLE
Fixed typo in class name

### PR DESCRIPTION
**Pull request by hason**
```markdown
### Fixed
- typo in class name
```

### CODE REVIEW

**Comment by greg0ire** [comment]
Are you targetting the right branch ?

**Comment by Soullivaneuh** [comment]
@greg0ire He is, `autocomplete.xml` does not exist on 1.x.

**Comment by OskarStark** [comment]
`RTM` after rebase

**Comment by hason** [comment]
Rebased. I'm sorry for delay.

**Comment by Soullivaneuh** [comment]
Thank you @hason

**Pull request merged**
