### PR TITLE
DevKit updates for 1.x branch

### PR DESCRIPTION
**Pull request by SonataCI**

### CODE REVIEW

**Comment by greg0ire** [comment]
The plan is to drop 5.3-7.0

**Comment by dbu** [comment]
i like the plan, but can we limit that plan to the master (2.x) branch?

**Comment by Soullivaneuh** [comment]
@dbu This was discussed and voted here: https://github.com/sonata-project/dev-kit/issues/285

Dropping dependencies support is semver compliant.

Two exceptions rules:

* We must support PHP under the green maintaining zone (except for php 7.0 for this time).
* We must support at least one LTS Symfony version if the package has SF dependencies.

This is a dev-kit update global for all projects.

**Comment by Soullivaneuh** [comment]
@dbu Another option: If you want to make it on 2.x this time, then we have to release a new major right now.

But next time, the versions dropping should follow #285.

**Comment by Soullivaneuh** [comment]
Correction: It's already released: https://github.com/sonata-project/SonataDoctrinePhpcrAdminBundle/releases/tag/2.0.0

At least if you want to make release yourself, it would be great to warn it on Slack. ;-)

Right now the base branch is not good for dev-kit. I'll fix this.

**Comment by dbu** [comment]
uh, i did not really follow all that much. max seems to have released. should we create a 2.x branch now and make that the default branch? or make master default until we decide that we need to break BC?

**Comment by Soullivaneuh** [comment]
> should we create a 2.x branch now and make that the default branch?

Yes. 2.x is now the stable branch and 1.x should not be maintained anymore.

Master is for BC breaking.

I'm managing that right now.

Ref: https://github.com/sonata-project/dev-kit/blob/master/project/CONTRIBUTING.md#the-base-branch

Please also note we dropped the three branches way support. Too heavy for the core: https://github.com/sonata-project/dev-kit/issues/284

**Comment by Soullivaneuh** [comment]
Closing this one. Please see: https://github.com/sonata-project/dev-kit/pull/300

**Comment by dbu** [comment]
thanks a lot!

**Pull request closed without merging**
