### PR TITLE
Fix tests for PHP 7.2

### PR DESCRIPTION
**Pull request by jordisala1991**
I am targeting this branch, because this is BC.

## Subject

This fixes tests for PHP 7.2

### CODE REVIEW

**Comment by jordisala1991** [comment]
I don't know what is happening with this bundle.. so many errors

**Comment by dbu** [comment]
looks like an endless loop with some versions of sonata admin: 

Sonata\DoctrinePHPCRAdminBundle\Tests\Resources\Admin\ContentAdmin->getClass() /home/travis/build/sonata-project/SonataDoctrinePhpcrAdminBundle/src/Admin/Admin.php:101
Sonata\DoctrinePHPCRAdminBundle\Tests\Resources\Admin\ContentAdmin->hasSubject() /home/travis/build/sonata-project/SonataDoctrinePhpcrAdminBundle/vendor/sonata-project/admin-bundle/src/Admin/AbstractAdmin.php:988

until maximum nesting level.

**Comment by jordisala1991** [comment]
Do you have an idea on how to fix this?

**Comment by jordisala1991** [comment]
This is included on the dev-kit PR now

**Pull request closed without merging**
