### PR TITLE
Handle no sort by value

### PR DESCRIPTION
**Pull request by VincentLanglet**
Same than https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/998

### CODE REVIEW

**Comment by VincentLanglet** [comment]
Same here @core23. :)

**Comment by VincentLanglet** [comment]
I can't merge this because of the failing build.

It fails since some commits https://github.com/sonata-project/SonataDoctrinePhpcrAdminBundle/commits/2.x
Do you have any idea why ? @core23 @OskarStark

**Comment by greg0ire** [comment]
The build says something interesting about `symfony/asset`: https://travis-ci.org/github/sonata-project/SonataDoctrinePhpcrAdminBundle/jobs/661970823#L495

**Comment by OskarStark** [comment]
Should be fixed by https://github.com/sonata-project/SonataDoctrinePhpcrAdminBundle/pull/581, can you please rebase?

**Comment by VincentLanglet** [comment]
There is still something wrong with the tests @OskarStark 
https://github.com/sonata-project/SonataDoctrinePhpcrAdminBundle/commits/2.x

**Comment by VincentLanglet** [comment]
@greg0ire I have the same issue with travis... :/

**Pull request merged**
