### PR TITLE
prepare release

### LINKED ISSUE #449: cleanup composer.json
there are a couple of `@dev` dependencies in composer.json. we have to move to stable versions of the dependencies before releasing.

### PR DESCRIPTION
**Pull request by ElectricMaxxx**
fix #449

### CODE REVIEW

**Comment by greg0ire** [comment]
This does not seem to have anything to do with #449

**Comment by greg0ire** [comment]
Ok now it does

**Comment by ElectricMaxxx** [comment]
switching branches in githubs seems not to work properly.

**Comment by ElectricMaxxx** [comment]
@greg0ire you know what is wrong with travis here?

**Comment by greg0ire** [comment]
Can't tell anymore since you closed the PR

**Pull request closed without merging**
