### PR TITLE
Fixed translation domain

### LINKED ISSUE #492: Incorrect translation domain used
#### Sonata packages

```bash
sonata-project/admin-bundle                3.x-dev 7ecdc8e The missing Symfony Admin Generator
sonata-project/block-bundle                3.x-dev b7b5e57 Symfony SonataBlockBundle
sonata-project/cache                       1.x-dev 2483918 Cache library
sonata-project/cache-bundle                2.x-dev 27e565a This bundle provides caching services
sonata-project/core-bundle                 3.x-dev 592f82c Symfony SonataCoreBundle
sonata-project/datagrid-bundle             2.x-dev eccf51c Symfony SonataDatagridBundle
sonata-project/doctrine-orm-admin-bundle   3.x-dev 4f92b57 Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/doctrine-phpcr-admin-bundle 2.0.0           Symfony Sonata / Integrate Doctrine PHPCR into the SonataAdminBundle
sonata-project/exporter                    1.x-dev c2fed82 Lightweight Exporter library
sonata-project/seo-bundle                  2.x-dev 66b114b Symfony SonataSeoBundle
```

#### Symfony packages

```bash
symfony/assetic-bundle     dev-master 2e0a23a Integrates Assetic into Symfony2
symfony/monolog-bundle     dev-master c9fb33a Symfony MonologBundle
symfony/phpunit-bridge     2.8.x-dev 34bfa4f  Symfony PHPUnit Bridge
symfony/polyfill-apcu      dev-master cec3239 Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-intl-icu  dev-master 4aa0b65 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  dev-master 7c8fae0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php54     dev-master b776342 Symfony polyfill backporting some PHP 5.4+ features to lower PHP versions
symfony/polyfill-php55     dev-master 29b1381 Symfony polyfill backporting some PHP 5.5+ features to lower PHP versions
symfony/polyfill-php56     dev-master e85ebde Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     dev-master b6482e6 Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util      dev-master 67925d1 Symfony utilities for portability of PHP codes
symfony/security-acl       dev-master ab4dfe2 Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle 2.6.x-dev 11555c3  Symfony SwiftmailerBundle
symfony/symfony            2.8.x-dev 6edfa4b  The Symfony PHP framework
```

## Subject

Wrong translation domain is used for tree tremplate. Domain 'SonataDoctrinePHPCRAdmin' is defined in translation files, but 'SonataDoctrinePhpcrAdminBundle' is used in one single template src/Resources/views/Tree/tree.html.twig

Missing translations:
```bash
Locale | Domain | Times used | Message ID | Message Preview
-- | -- | -- | -- | --
en | SonataDoctrinePhpcrAdminBundle | 1 | create_item | create_item
en | SonataDoctrinePhpcrAdminBundle | 1 | delete_item | delete_item

### PR DESCRIPTION
**Pull request by nvbooster**
Closes #492

### Changelog

```markdown
### Fixed
- Bad translation domain tree template
```

### CODE REVIEW

**Comment by ElectricMaxxx** [comment]
@greg0ire your own bot hit you, awesome :-)

**Comment by greg0ire** [comment]
Hey there!

It looks like you did not fill the pull request template properly. Maybe you
were confused, so let me help you go through this step by step.

# Explaining why you target this branch

> I am targeting this branch, because {reason}.

Here, you are supposed to replace `{reason}` with something like:

- "there is a BC-break" if you picked the master branch
- "there is no BC-break" if you picked the stable branch

# Searching and finding related issues

You did that one just great, good job!

# Filling the changelog

That one is really important to get right, because it will be used to craft a
release changelog such as [this
one](https://github.com/sonata-project/SonataAdminBundle/releases/tag/3.23.0).
The first thing you need to know about this is that if your pull request is
pedantic, meaning it does not fix a bug for the user, or adds a new feature, it
is not needed. This is typically the case for PRs that fix the build or add
some documentation.

3 important things:

1. Make sure to fill the changelog section with something directed at the end
user, that answers the question "What benefit do I get from upgrading?".
2. Make sure to remove empty sections.
3. Make sure to keep the markdown markup.



## Filling the Subject

Last but not least, describe your PR as well as you can. Bear in mind that some
reviewers do not even use the library they are maintaining, so try to be
crystal clear.

**Comment by Soullivaneuh** [comment]
I updated your changelog. You should describe what you change in general.

**Comment by dbu** [comment]
thank you!

**Pull request merged**
