### PR TITLE
Prepare new release

### LINKED ISSUE #449: cleanup composer.json
there are a couple of `@dev` dependencies in composer.json. we have to move to stable versions of the dependencies before releasing.

### PR DESCRIPTION
**Pull request by ElectricMaxxx**
just a clean up before the new release fix #449

### CODE REVIEW

**Comment by ElectricMaxxx** [comment]
argh, seems as i would have to increas coverage before releasing

**Comment by greg0ire** [comment]
No you don't have to, it's not marked as required. You do have to fix the tests though :P

**Comment by ElectricMaxxx** [comment]
Uhh and that is strange. It is just a single build. And there each request on some http tooks to much time. 
Btw why do we download a phpunit.phar, thought we use simple-phpunit?

**Comment by greg0ire** [comment]
[We want to](https://github.com/sonata-project/dev-kit/issues/197), but nobody has made a PR to change that yet.

**Comment by ElectricMaxxx** [comment]
I will give it a try later or tomorrow morning. But the main problem looks more like the container has bad connectivity.

**Comment by greg0ire** [comment]
I don't think so. I think the SAT solver is stuck. Maybe try bumping version constraints to the nearest patch version? @dbu had a similar issue IIRC, solved it using `travis_wait` I think

**Comment by ElectricMaxxx** [comment]
But the test call comes from make file, so that also comes from dev-kit?

**Comment by greg0ire** [comment]
...which helps me find what I was talking about: https://github.com/sonata-project/dev-kit/commit/768f3d66d8b146e9f00c278ef66764b6388bb8bd

**Comment by ElectricMaxxx** [comment]
Oh, i tought to go on RC tonight :-(

**Comment by greg0ire** [comment]
Like I said, You can always try bumping e.g `^1.0` to `^1.0.42`, it could help, because it changes the space of the possibilities composer has to evaluate, but aside from that, sorry I have no solution.

**Comment by ElectricMaxxx** [comment]
So, the solution seems not to work. Or the time is not enough. 

But wait, i released tree-browser-bundle with `min-stability:RC` - unfortunatly. Can that be a reason for composer not to resolve a stable package, which i request here?

**Comment by greg0ire** [comment]
> So, the solution seems not to work. Or the time is not enough.

What makes you say that? The commit from @dbu has not landed on master.

**Comment by greg0ire** [comment]
> But wait, i released tree-browser-bundle with min-stability:RC - unfortunatly. Can that be a reason for composer not to resolve a stable package, which i request here?

No idea, and also, touching that setting or even using @dev in a library does not sound great, even on a master branch. This should only be used in projects IMO, it's a hack.

**Comment by ElectricMaxxx** [comment]
@greg0ire i removed that notice as i saw your answer.

**Comment by ElectricMaxxx** [comment]
The [tree-browser-bundle Release](https://github.com/symfony-cmf/tree-browser-bundle/releases/tag/2.0.1) saved my PR :-)

Ready to merge and RC-1 i would say then.

**Comment by greg0ire** [comment]
Good job!

**Pull request merged**
