### PR TITLE
Bump every dep to its latest patch version

### PR DESCRIPTION
**Pull request by greg0ire**
This will reduce the space of possible versions and hopefully, fix the
prefer-lowest build.

### CODE REVIEW

**Comment by dbu** [comment]
this should normally be fine. though it might trip up some people on edge cases, where they pin to a lower patch version because of some obscure incompatibility between dependencies. (every bugfix is a small BC break somehow)

**Comment by greg0ire** [comment]
> this should normally be fine. though it might trip up some people on edge cases, where they pin to a lower patch version because of some obscure incompatibility between dependencies. (every bugfix is a small BC break somehow)

Yeah not great, but should be fine indeed.

@lsmith77 and @Soullivaneuh 's bots are fighting over labels lol

**Comment by dbu** [comment]
@lsmith77 can you remove your bot from the sonata project please?

can you do the pull request from 1.x to master? there will be conflicts because composer.json looks quite a bit different... i did a branch from master, merged 1.x into it and solved the conflicts and then did a PR with that against master.

**Comment by greg0ire** [comment]
Oh... so maybe my fix won't fix anything after all...

**Comment by greg0ire** [comment]
See #451

**Pull request merged**
