### PR TITLE
trying to fix lowest-version build

### PR DESCRIPTION
**Pull request by dbu**
on master, the lowest-version build times out (#440). trying to see if restricting the dependencies a bit helps composer find a solution.

this is not mergeable because .travis/ is managed by dev-kit...

### CODE REVIEW

**Comment by dbu** [comment]
@greg0ire so this change would fix the problem for us. but i guess the file is managed by dev-kit, so its not really a solution. any idea how we can achieve this with dev-kit?

**Comment by greg0ire** [comment]
First, let's see how #450 goes, shall we?

**Comment by greg0ire** [comment]
@dbu it seems to be working. Do you like my solution?

**Comment by dbu** [comment]
the problem is only with master, not with the 1.x branch. i merged your pr to 1.x but now we need the same for master.

**Comment by Soullivaneuh** [comment]
This is why I added [`travis_wait`](https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received) before on dev-kit.

This was removed because "no build is under timeout now" but I think this should be restored, by prevention.

@dbu Could you try with this method on this PR?

**Comment by dbu** [comment]
lets see if waiting is enough

**Comment by dbu** [comment]
yay! see https://github.com/sonata-project/dev-kit/pull/252

**Pull request closed without merging**
