### PR TITLE
Fix Symfony deprecated feature usages

### PR DESCRIPTION
**Pull request by dbu**
continuation of #348

### CODE REVIEW

**Comment by dbu** [comment]
@WouterJ i'd say this looks good to merge? 
no idea what the sonataci complains about, it says 0 failures but puts a red icon...

**Comment by greg0ire** [comment]
Sonata CI does complain about something : http://91.121.3.21/job/sonata-ci-bundle-doctrine-phpcr-admin/26/console

**Comment by greg0ire** [comment]
```
Loaded config from "/project/.php_cs"
.....................................................................................
Legend: ?-unknown, I-invalid file syntax, file ignored, .-no changes, F-fixed, E-error
Checked all files in 13.742 seconds, 7.500 MB memory used
PHPUnit 5.3.0 by Sebastian Bergmann and contributors.

.WW......................................W.....................  63 / 108 ( 58%)
...................W.........................                   108 / 108 (100%)

Time: 292 ms, Memory: 13.50Mb

There were 4 warnings:

1) Sonata\DoctrinePHPCRAdminBundle\Tests\Builder\ListBuilderTest::testAddField
Trying to configure method "getModelManager" which cannot be configured because it does not exist, has not been specified, is final, or is static

2) Sonata\DoctrinePHPCRAdminBundle\Tests\Builder\ListBuilderTest::testAddFieldNullType
Trying to configure method "getModelManager" which cannot be configured because it does not exist, has not been specified, is final, or is static

3) Sonata\DoctrinePHPCRAdminBundle\Tests\Filter\BooleanFilterTest::testFilterEmptyArrayDataWithMeaninglessValue
Trying to configure method "andWhere" which cannot be configured because it does not exist, has not been specified, is final, or is static

4) Sonata\DoctrinePHPCRAdminBundle\Tests\Filter\NodeNameFilterTest::testFilterEmptyArrayDataWithMeaninglessValue
Trying to configure method "andWhere" which cannot be configured because it does not exist, has not been specified, is final, or is static

WARNINGS!
```

**Comment by dbu** [comment]
ah, okay. seems we mock something in a strange way.

but not related to this PR, so i simply merged.

**Comment by greg0ire** [comment]
Yes it is a bug we encountered in several libs because phpunit is getting more strict.

**Comment by greg0ire** [comment]
See @jvasseur 's https://github.com/jvasseur/SonataAdminBundle/commit/8f74210bfb0ca37fb342be5d3f59c8151d23053a

**Comment by patkar** [comment]
backref: sulu/sulu#2106

**Pull request merged**
