### PR TITLE
Add Symfony 2.8 support

### PR DESCRIPTION
**Pull request by WouterJ**
As of Symfony 2.8, form type names are deprecated and FQCN are used. This means none of the options of this contractor were applied, resulting in many issues trying  to use the admin panels.

### CODE REVIEW

**Comment by OskarStark** [comment]
can you add some tests or extend existing tests (if there are some) with the new class names?

**Comment by rande** [comment]
@WouterJ an alternative approach can be : https://github.com/sonata-project/SonataAdminBundle/commit/3e7ad359411a5f4ae119d9dc3ef26b3e44716fd1#diff-baa44e28e0e16fee196ae10cb9a3fb46

**Comment by WouterJ** [comment]
@rande yeah, but in 2.8 we have to support both the name and FQCN. So I thought just checking class and name was the easiest.

**Comment by rande** [comment]
Yes, the feature provided by the core bundle will help to have compatibility with sf3.0 and sf2.8 with the 2.4 version of Sonata.

Will will remove those with the version 3.0 of sonata, to be only compatible with symfony3.0.

**Comment by dbu** [comment]
@rande are you asking to port this change to use the FormHelper as in https://github.com/sonata-project/SonataAdminBundle/commit/3e7ad359411a5f4ae119d9dc3ef26b3e44716fd1#diff-baa44e28e0e16fee196ae10cb9a3fb46 ? @WouterJ do you see any problems with that? i can work at this this afternoon if we agree it makes sense.

**Comment by rande** [comment]
@dbu not really, it is just an alternative. FormHelper solution will just make easier to remove the support ;) But @WouterJ works too.

**Comment by WouterJ** [comment]
FormHelper won't help much in the code, as 2.8 requires to accept *both* FQCN and type name (type names are only deprecated, not removed. So code would look like:
```php
FormHelper::registerTypeMapping(array(
    'sonata_type_admin' => 'Sonata\AdminBundle\Form\Type\AdminType',
));

switch ($type) {
    case 'sonata_type_admin':
    case FormHelper::getTypeMapping('sonata_type_admin'):
        // ...
}
```

**Comment by dbu** [comment]
so do we agree its ok to merge this as is?

probably not related to this change, but it looks like when we do not specify the symfony version, we end up missing part of the security things - see the build fails.

**Comment by WouterJ** [comment]
Can this please be merged?

**Comment by lsmith77** [comment]
@WouterJ see @dbu's comment about the security component issue on travis ..

**Comment by WouterJ** [comment]
@lsmith77 but that's not related to this PR... (I can of course fix it in this PR, but it shouldn't be a blocker for merging imo)

**Comment by lsmith77** [comment]
well its always iffy when tests are failing when merging a PR ..
also .. I guess 2.8.* should be removed from the allowed failures

**Comment by WouterJ** [comment]
This will fix the build error: https://github.com/sonata-project/SonataAdminBundle/pull/3487

**Comment by dbu** [comment]
i just commented on the admin bundle fix about security-acl. lets hope it can quickly be merged.

can you move out symfony 2.8 from the allowed failures please?

**Comment by rande** [comment]
oups ... wrong PR ...

**Comment by dbu** [comment]
no worries, we can keep it merged and i fix the 2.8 thing in master

**Comment by rande** [comment]
@dbu I merged the related PR ... https://github.com/sonata-project/SonataAdminBundle/pull/3487#issuecomment-164494979

**Comment by dbu** [comment]
thanks! and just pushed something to see if 2.8 does not fail.

**Comment by WouterJ** [comment]
Hmm, this now of course has only made it into 2.0-dev. Is it an option to backport this to 1.3?

**Comment by dbu** [comment]
oh, yeah i guess that would make sense. do you want to try that wouter?

**Comment by WouterJ** [comment]
See https://github.com/sonata-project/SonataDoctrinePhpcrAdminBundle/pull/351

**Pull request merged**
